# Generated by Django 2.2.3 on 2019-07-25 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('', '------'), ('Billing', 'Billing'), ('Building', 'Building'), ('Residential', 'Residential'), ('Office', 'Office')], max_length=32, verbose_name='Address Type')),
                ('line_1', models.CharField(max_length=254, verbose_name='Address')),
                ('line_2', models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name='Ste or Apt')),
                ('city', models.CharField(max_length=32)),
                ('zip', models.CharField(max_length=8)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ('line_1',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('name_plain', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('dial_code', models.CharField(blank=True, max_length=4, null=True)),
                ('flag', models.CharField(blank=True, max_length=4, null=True)),
                ('capital', models.CharField(blank=True, max_length=64, null=True)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('region_des', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utc', models.CharField(db_index=True, max_length=64, verbose_name='utc')),
                ('label', models.CharField(max_length=64, verbose_name='label')),
                ('alias', models.CharField(max_length=8, verbose_name='alias')),
                ('offset', models.IntegerField(verbose_name='offset')),
                ('is_dst', models.BooleanField(verbose_name='is dst')),
                ('description', models.CharField(max_length=128, verbose_name='description')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezones',
                'ordering': ('offset',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('capital', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('appellation', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('country', models.ForeignKey(db_column='country', default='us', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='name')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('fax', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='fax')),
                ('email', models.EmailField(max_length=128, verbose_name='email')),
                ('website', models.URLField(blank=True, default=None, max_length=254, null=True, verbose_name='website')),
                ('facebook', models.URLField(blank=True, default=None, max_length=254, null=True, verbose_name='facebook link')),
                ('twitter', models.URLField(blank=True, default=None, max_length=254, null=True, verbose_name='twitter link')),
                ('linkedin', models.URLField(blank=True, default=None, max_length=254, null=True, verbose_name='linkedIn link')),
                ('instagram', models.URLField(blank=True, default=None, max_length=254, null=True, verbose_name='instagram link')),
                ('youtube', models.URLField(blank=True, default=None, max_length=254, null=True, verbose_name='youtube channel')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('addresses', models.ManyToManyField(related_name='companies', to='core.Address')),
                ('timezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Timezone')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('name',),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default='us', on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.State'),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
